name: birthday-server
services:
  birthday:
    build:
      context: .
      dockerfile: ./deployments/birthday/Dockerfile
    container_name: birthday-server
    env_file:
      - ./config/.env
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    command: >
        sh -c "echo 'Migrating main database' &&
              ./tern migrate -c db/migrations/public/tern.conf -m db/migrations/public/ &&
              echo 'Finished main database migrations' &&
              echo 'Starting birthday server' &&
              ./birthday"
  
  db:
    image: postgres:latest
    container_name: birthday-db
    env_file:
      - ./config/.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5